#!/bin/bash

if [ ! -d "venv" ]; then
    echo "Install venv..."
    python3 -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
    echo "[Done] venv"
fi

# link mknote-activate to ~/.bin
echo "Link mknote-activate to ~/.bin ..."
mkdir -p ~/.bin
sed -i "s|PATH_TO_MKNOTE|`pwd`|g" bin/mknote-activate
ln -sf `pwd`/bin/mknote-activate ~/.bin
echo "[Done] link mknote-activate to ~/.bin"
