site_name: My Notes
theme:
  name: material
  font:
    text: Nerd Font
    code: Nerd Font Mono
  icon:
    logo: material/rocket
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.expand
    - navigation.sections
    - navigation.tracking
    - navigation.indexes
    - navigation.search.highlight
    - navigation.search.shareable
    - navigation.search.suggest
    - navigation.search.language
    - content.code.annotate
    - content.code.copy
    - content.code.tabs
    - content.code.highlight
    - content.code.inlinehilite
    - content.code.superfences
    - content.code.snippets
    - content.admonition.details
  palette:
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: green
      accent: deep purple

    # White mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: blue 
      accent: deep orange



markdown_extensions:
  # Emoji Supports
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # Syntax highlighting for code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

  # Admonition
  - admonition:
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jackhong12

plugins:
  - obsidian-interactive-graph
  - search
  - ezlinks

extra_javascript:
  - https://fastly.jsdelivr.net/npm/jquery/dist/jquery.min.js
  - https://fastly.jsdelivr.net/npm/echarts/dist/echarts.min.js
  - assets/javascripts/interactive_graph.js

extra_css:
  - assets/stylesheets/interactive_graph.css

copyright: Copyright © 2025 Zhen-Hong (Jack) Huang
